server:
  port: 8091
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: mgroup-stats-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${STAT_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  #mvc:
  #  format:
  #    date: yyyy-MM-dd
  #    date-time: yyyy-MM-dd HH:mm:ss
  #    time: HH:mm:ss